# clearing workspace
rm(list = ls())
graphics.off()
cat("\014")

# --------------------------------------------------------------------
## Header ##
# Running title: Moisture limits the diversity of nesting bees, wasps,
# and parasitoids in lying and standing deadwood
# Author: Massimo Martini
# Date: 28th August 2026

# Description: This script runs the sampling completeness, main GLMM, and
# community composition analyses used in the manuscript

# Set working directory to project root:

# setwd()

# Reproducibility: run with R 4.6.1 and use the package versions
# recorded in renv.lock. The supplied .Rprofile activates renv;
# if needed, run:

# source("renv/activate.R"),
# renv::restore(retry = FALSE)
# renv::status()

# --------------------------------------------------------------------
## Comments ##
# For simplicity, we leave out all diagnostic and plotting procedures

# --------------------------------------------------------------------
# 1. Load libraries and source functions
# --------------------------------------------------------------------

library(vegan)
library(dplyr)
library(tidyverse)
library(glmmTMB)
library(performance)
library(DHARMa)
library(car)
library(iNEXT)
library(betapart)
library(lme4)
library(indicspecies)
library(broom.mixed)
library(pairwiseAdonis)

source("deadwd_functions.R")

# Keep all files generated by this script in one directory.
deadwd_output_dir <- "deadwd_script_output"
dir.create(deadwd_output_dir, recursive = TRUE, showWarnings = FALSE)

# --------------------------------------------------------------------
# 2. Read and prepare data for analysis
# --------------------------------------------------------------------
log_data <- readr::read_csv("log_data.csv")
insect_data <- readr::read_csv("deadwd_insect_data.csv")

# calculate and transform variables
log_data$log_tr = log2(log_data$tree_r) #log-transformation of tree richness prior to scaling

log_data <- log_data %>%
  mutate(host_ab_tot = (par_abund + host_abund)) #calculate total host abundance

log_data <- log_data %>%
  mutate(p_rate = (par_abund / (par_abund + host_abund))) #calculate parasitism rate

log_data$log_hatot <- log1p(log_data$host_ab_tot) #log-transform host abundance

log_data$log_pa <- log1p(log_data$par_abund) #log-transform parasitoid abundance

log_data$log_anttrap <- log1p(log_data$ant_trap) # log-transform ant abundance

log_data$rt_cwd <- sqrt(log_data$cwd_vol_imp) #square-root transform coarse-woody-debris volume

log_data$mc_new <- pmin(pmax(log_data$mc_mass, 0.0001), 1 - 0.0001) #reducing one value above 1 to slightly smaller than 1


#checking for correlations between variables
vars <- log_data[, c("log_tr", "cnpy_prop", "wantoc_imp", "host_ab_tot", "host_rich","par_abund", 
                     "par_rich", "ant_pres", "mc_imp", "cwd_vol_imp")]

cortable <- cor(vars, use = "complete.obs", method = "pearson")
cortable

cortable %>% 
  as.data.frame() %>% 
  rownames_to_column("var1") %>% 
  pivot_longer(-var1, names_to = "var2", values_to = "cor") %>% 
  filter(var1 < var2, abs(cor) > 0.50) %>% 
  arrange(desc(abs(cor))) # strong correlations between same-trophic-level abundance and richness

# change variables in factors with reference level
log_data$position <- as.factor(log_data$position)
log_data$treatment <- as.factor(log_data$treatment)
log_data$position <- relevel(log_data$position, ref = "S") # standing deadwood reference
log_data$treatment <- relevel(log_data$treatment, ref = "nA") # standing deadwood with ant exclusion reference

log_data$host_pres <- ifelse(log_data$host_ab_tot > 0, 1, 0) # calculate host presence/absence

log_data$ant_pres <- as.factor(log_data$ant_pres)
log_data$host_pres <- as.factor(log_data$host_pres)
log_data$geo_cat <- as.factor(log_data$geo_cat)
log_data$geo_cat <- relevel(log_data$geo_cat, ref = 1)

# --------------------------------------------------------------------
# 3. Exploratory analyses and scaling variables ####
# --------------------------------------------------------------------

table(log_data$treatment, log_data$host_ab_tot > 0) # number of logs with hosts per treatment
table(log_data$treatment, log_data$ant_trap > 0) # number of logs with ants per treatment
table(log_data$treatment, log_data$par_abund > 0)

with(insect_data,
     tapply(morphotype, list(treatment, level), function(x) length(unique(x)))) #species per treatment

with(
  subset(insect_data, level == "host"),
  tapply(morphotype, location, function(x) length(unique(x)))
) # Overall, 25 host species in standing and 8 in lying deadwood

# How many host species are unique in standing vs lying deadwood?
standing_species <- unique(insect_data$morphotype[
  insect_data$level == "host" & insect_data$location == "S"
])
lying_species <- unique(insect_data$morphotype[
  insect_data$level == "host" & insect_data$location == "G"
])
standing_only_species <- setdiff(standing_species, lying_species)
lying_only_species <- setdiff(lying_species, standing_species)

cat("Host species unique to standing deadwood:",
    length(standing_only_species), "\n",
    paste(sort(standing_only_species), collapse = ", "), "\n")
cat("Host species unique to lying deadwood:",
    length(lying_only_species), "\n",
    paste(sort(lying_only_species), collapse = ", "), "\n")


# Comparing gmc variance between treatments
# Levene / Brown-Forsythe 
car::leveneTest(mc_mass ~ position, data = log_data, center = median)

tapply(log_data$mc_mass, log_data$position, IQR, na.rm = TRUE)

var_G  <- with(log_data, var(mc_mass[position=="G"],  na.rm=TRUE))
var_A  <- with(log_data, var(mc_mass[position=="S"],  na.rm=TRUE))

var_G / var_A # 1.8x
# lying deadwood has about twice the mean and variance in moiture content compared to standing


#Scaling all variables for modeling
#set new abbreviated scaled column names
name_map <- c(
  log_tr       = "sc_logtr",
  cnpy_prop    = "sc_cnpy",
  log_hatot    = "sc_loghatot",
  host_rich    = "sc_hr",
  log_pa       = "sc_logpa",
  par_rich     = "sc_pr",
  rt_cwd       = "sc_cwd",
  wantoc_imp   = "sc_wantoc",
  log_anttrap  = "sc_logant",
  mc_imp       = "sc_mc"
)

#scale all selected variables in both dataframes
for (old in names(name_map)) {
  new <- name_map[[old]]
  log_data[[new]] <- as.numeric(scale(log_data[[old]]))
}

#scaling moisture content within each deadwood treatment
name_map_tr <- c(
  mc_imp       = "sc_mctr")

# function to scale  variables within-treatment
scale_within_treatment <- function(df, name_map, tr_var = "treatment") {
  
  for (old in names(name_map)) {
    new <- name_map[[old]]
    df[[new]] <- NA_real_
    
    for (tr in unique(df[[tr_var]])) {
      idx <- df[[tr_var]] == tr
      x   <- df[[old]][idx]
      
      if (sd(x, na.rm = TRUE) == 0) {
        df[[new]][idx] <- 0
      } else {
        df[[new]][idx] <- as.numeric(scale(x))
      }
    }
  }
  
  df
}

log_data <- scale_within_treatment(
  df       = log_data,
  name_map = name_map_tr
)

# --------------------------------------------------------------------
# 4. Sampling completeness ####
# --------------------------------------------------------------------


log_data <- log_data %>%
  mutate(
    site    = factor(site),
    plot_id = factor(plot_id),
    treatment = factor(treatment),
    sample_id = interaction(site, plot_id, treatment, drop = TRUE)
  )

insect_data <- insect_data %>%
  mutate(
    treatment = factor(treatment),
    plot_id   = factor(plot_id),
    site      = factor(site),
    level     = factor(level)
  )

hosts <- insect_data %>%
  filter(level == "host")

hosts <- hosts %>%
  mutate(sample_id = interaction(site, plot_id, treatment, drop = TRUE))

host_comm <- hosts %>%                    # Species-by-log trap matrix
  group_by(sample_id, morphotype) %>%
  summarise(abund = sum(number_individuals), .groups = "drop") %>%
  tidyr::pivot_wider(
    names_from  = morphotype,
    values_from = abund,
    values_fill = 0
  )


host_df <- host_comm %>%
  left_join(log_data %>% dplyr::select(sample_id, plot_id, site, treatment),
            by = "sample_id")

#overall pooled sampling completeness
host_abund_only <- host_df[, !(names(host_df) %in% c("sample_id","plot_id","site","treatment"))]
host_totals     <- colSums(host_abund_only)

set.seed(123)
out_host_all <- iNEXT(host_totals,
  datatype = "abundance", nboot = 100
) # Quick-run setting: reduced from the 1,000 replications used
out_host_all$DataInfo$SC   # global sample coverage for hosts = 99%

#treatment x site assemblages
host_by_trtsite <- host_df %>%
  mutate(trt_site = paste(treatment, site, sep = "_")) %>%
  group_by(trt_site) %>%
  summarise(across(where(is.numeric), sum), .groups = "drop")

# Make species-by-assemblage matrix
host_comm_trtsite <- as.data.frame(t(host_by_trtsite[, -1]))
colnames(host_comm_trtsite) <- host_by_trtsite$trt_site

set.seed(123)
out_host_trtsite <- iNEXT(host_comm_trtsite, 
  datatype = "abundance", nboot = 100
) # Quick-run setting: reduced from the 1,000 replications used
out_host_trtsite$DataInfo # pooled sample coverage for each treatment & site

#plot x species assemblages
host_plot <- host_df %>%
  group_by(plot_id) %>%
  summarise(across(where(is.numeric), sum), .groups = "drop")

# Species-only matrix
host_abund_plot <- host_plot[, -1]
rownames(host_abund_plot) <- host_plot$plot_id

chao_sample_coverage <- function(x) {
  x <- x[x > 0]
  n  <- sum(x)
  if (n == 0) return(NA_real_)
  f1 <- sum(x == 1)
  f2 <- sum(x == 2)
  if (f1 == 0) return(1)
  if (f2 > 0) {
    1 - (f1 / n) * ((n - 1) * f1 / ((n - 1) * f1 + 2 * f2))
  } else {
    1 - (f1 / n) * ((n - 1) * (f1 - 1) / ((n - 1) * (f1 - 1) + 2))
  }
}

host_SC_plot <- apply(host_abund_plot, 1, chao_sample_coverage)

SC_plot_df <- data.frame(
  plot_id   = rownames(host_abund_plot),
  host_SC   = host_SC_plot,
  row.names = NULL
)

mean(SC_plot_df$host_SC) # mean per plot is 94%

#log-level
host_mat <- host_comm %>%
  as.data.frame()

rownames(host_mat) <- host_mat$sample_id
host_mat$sample_id <- NULL

# Host Shannon diversity per trap. Traps without host emergence are absent
# from host_mat and are assigned Shannon diversity of zero.
host_shannon_log <- vegan::diversity(host_mat, index = "shannon")
log_data$host_shannon <- host_shannon_log[
  match(as.character(log_data$sample_id), names(host_shannon_log))
]
log_data$host_shannon[is.na(log_data$host_shannon)] <- 0

# --------------------------------
## calculating estimated species richness based on 90% sample coverage
# for sensitivity check

# Species-only matrix with sample_id as rownames

# Turn each row into an abundance vector
host_list <- apply(host_mat, 1, function(x) x[x > 0])  # keep positive counts only
host_list <- host_list[lengths(host_list) > 0]         # drop logs with n = 0

# Trap-level estimates are uncertain for sparse assemblages.
# Some q = 0 estimates also extrapolate beyond twice the observed sample size;
# interpret this sensitivity analysis cautiously.
set.seed(123)
# Estimate diversity at fixed sample coverage (SC = 0.90)
est_list <- lapply(names(host_list), function(id) {
  x <- host_list[[id]]
  
  # estimateD returns a data.frame; we keep q=0 (richness)
  ed <- estimateD(
    x,
    datatype = "abundance",
    base     = "coverage",
    level    = 0.90,
    conf     = 0.95,
    nboot = 100
  ) # Quick-run setting: reduced from the 1,000 replications used
  
  # Keep richness row (Order.q == 0)
  ed0 <- ed %>% filter(Order.q == 0)
  
  ed0$sample_id <- id
  ed0
})

host_rich_SC90 <- bind_rows(est_list)

# observed SC per log
host_SC_log <- sapply(host_list, chao_sample_coverage)

SC_log_df <- data.frame(
  sample_id = names(host_SC_log),
  host_SC   = host_SC_log,
  row.names = NULL
)

mean(SC_log_df$host_SC) # mean SC per log is 95%

host_rich_SC90 <- host_rich_SC90 %>%
  left_join(SC_log_df, by = "sample_id")


# applying filter for species estimation based on sample coverage cutoff
dat_SC90_ok <- host_rich_SC90 %>%
  filter(host_SC >= 0.6)

log_data <- log_data %>% 
  left_join(dat_SC90_ok %>% dplyr::select(sample_id, qD),
            by = "sample_id")

qD_mod <- glmmTMB(log1p(qD) ~ treatment + sc_mctr + ant_pres +
                    sc_logtr + sc_cnpy + 
                    sc_loghatot +
                    (1|plot_id),
                  data = log_data,
                  family = gaussian()) # only host abundance affects qD, same as for raw species richness

# --------------------------------------------------------------------
# 5. GLMMs ####
# --------------------------------------------------------------------

###
# ------ Moisture content
###
#log gravimetric moisture content
mc_mod <- glmmTMB(mc_new ~ treatment + sc_logtr + sc_cnpy +
                    geo_cat +
                    (1 | site/plot_id),
                  data = log_data,
                  dispformula = ~ site + treatment,
                  family = beta_family())

###
# ------ Ants
###
ap_mod <- glmmTMB(ant_pres ~ treatment + sc_logtr + 
                    sc_wantoc +  sc_cnpy + geo_cat +
                    (1| site/plot_id),
                  data = log_data,
                  family = binomial())

###
# ------ Hosts
###
# presence
hp_mod <- glmmTMB(host_pres ~ treatment + site + ant_pres +
                    (1| plot_id),
                  data = log_data,
                  family = binomial())
# site and treatment directly affect the probability of log occupation

# abundance - moisture content scaled within treatments
ha_mod <- glmmTMB(host_ab_tot ~ treatment + sc_logtr + sc_mctr + ant_pres +
                    sc_cnpy + sc_cwd + 
                    (1 | site/plot_id),
                  data = log_data,
                  ziformula = ~ site + treatment,
                  family = nbinom2())

# abundance - moisture content scaled across treatments
ha_mod2 <- glmmTMB(host_ab_tot ~ treatment + sc_logtr + sc_mc + ant_pres +
                    sc_cnpy + sc_cwd + 
                    (1 | site/plot_id),
                  data = log_data,
                  ziformula = ~ site + treatment,
                  family = nbinom2())

# abundance - design
ha_mod_exp <- glmmTMB(host_ab_tot ~ treatment + sc_logtr +
                        (1 | site/plot_id),
                      data = log_data,
                      ziformula = ~ site + treatment,
                      family = nbinom2())

# species richness
hr_mod <- glmmTMB(host_rich ~ treatment + sc_mctr +
                    sc_logtr + sc_cnpy + sc_loghatot + sc_cwd +
                    (1 | plot_id),
                  data = log_data,
                  family = genpois())

# Site random intercept approaches zero resulting in singular fit
# It was thus removed.
# Check resulting model with:
# check_singularity(hr_mod)
# hr_mod$fit$convergence
# hr_mod$sdr$pdHess
# Note the unusually large Z statistic for host abundance
# denoting the high correlation with host richness

# species richness - removed host abundance
hr_mod2 <- glmmTMB(host_rich ~ treatment + sc_mctr + ant_pres +
                     sc_logtr + sc_cnpy + sc_cwd +
                     (1 | site/plot_id),
                   data = log_data,
                   family = poisson())

#species richness - design
hr_mod_exp <- glmmTMB(host_rich ~ treatment + sc_logtr +
                        (1 | site/plot_id),
                      data = log_data,
                      ziformula = ~ site + treatment,
                      family = genpois())

###
# ------ Parasitoids
###

log_data_p <- subset(log_data, host_ab_tot > 0)
# only logs with evidence of host brood through host or
# parasitoid emergence are considered

# abundance
pa_mod <- glmmTMB(par_abund ~ treatment + sc_mctr + ant_pres +
                    sc_logtr + sc_cnpy + sc_loghatot + sc_cwd +
                    (1 | site/plot_id),
                  data = log_data_p,
                  family = nbinom2())

# abundance - removed host abundance (no mediation)
pa_mod2 <- glmmTMB(par_abund ~ treatment + ant_pres + sc_mctr +
                     sc_logtr + sc_cnpy + sc_cwd +
                     (1 | site/plot_id),
                   data = log_data_p,
                   family = nbinom2())

# abundance - design
pa_mod_exp <- glmmTMB(par_abund ~ treatment + sc_logtr +
                        (1 | site/plot_id),
                      data = log_data_p,
                      family = nbinom1())

# species richness
pr_mod <- glmmTMB(par_rich ~ treatment + ant_pres + sc_mctr +
                    sc_logtr + sc_cnpy + sc_logpa +
                    (1 | plot_id),
                  data = log_data_p,
                  family = poisson())
# Site random intercept approaches zero resulting in singular fit
# It was thus removed.
# Model is underdispersed due to high correlation between parasitoid
# abundance and richness (r = 0.87).
# This model is to be interpreted with caution.

# species richness - replace parasitoid abundance with host abundance
pr_mod2 <- glmmTMB(par_rich ~ treatment + sc_loghatot + ant_pres + sc_mctr +
                     sc_logtr + sc_cnpy +
                     (1 | site/plot_id),
                   data = log_data_p,
                   family = poisson())

#species richness - design
pr_mod_exp <- glmmTMB(par_rich ~ treatment + sc_logtr +
                      (1 | plot_id),
                      data = log_data_p,
                      family = poisson())
# Site random intercept approached zero, resulting
# in singular fit. It was thus removed.

###
# ------ Parasitism
###
# parasitism
p_modd <- glmmTMB(cbind(par_abund, host_abund) ~ treatment + sc_mctr + ant_pres +
                    sc_pr + sc_hr + 
                    sc_logtr + sc_cnpy +
                    (1 | site/plot_id),
                  data = log_data_p,
                  family = betabinomial())

# parasitism - removed host and parasitoid richness (no direct diversity effects)
p_modd2 <- glmmTMB(cbind(par_abund, host_abund) ~ treatment + sc_mctr + ant_pres +
                     sc_logtr + sc_cnpy +
                     (1 | site/plot_id),
                   data = log_data_p,
                   family = betabinomial())

#parasitism - design
p_modd_exp <- glmmTMB(cbind(par_abund, host_abund) ~ treatment + sc_logtr +
                        (1 | site/plot_id),
                      data = log_data_p,
                      family = betabinomial())

models <- list(
  Moisture              = mc_mod,
  Ant_occurrence        = ap_mod,
  Host_occurrence       = hp_mod,
  Host_abundance        = ha_mod,
  Host_abundance_alternative = ha_mod2,
  Host_abundance_design = ha_mod_exp,
  Host_richness         = hr_mod,
  Host_richness_2       = hr_mod2,
  Host_richness_design  = hr_mod_exp,
  Parasitoid_abundance  = pa_mod,
  Parasitoid_abundance_2 = pa_mod2,
  Parasitoid_abundance_design = pa_mod_exp,
  Parasitoid_richness   = pr_mod,
  Parasitoid_richness2  = pr_mod2,
  Parasitoid_richness_design = pr_mod_exp,
  Parasitism            = p_modd,
  Parasitism_2          = p_modd2,
  Parasitism_design     = p_modd_exp
)

rm(
  list = c(
    "mc_mod", "ap_mod", "hp_mod",
    "ha_mod", "ha_mod2", "ha_mod_exp",
    "hr_mod", "hr_mod2", "hr_mod_exp",
    "pa_mod", "pa_mod2", "pa_mod_exp",
    "pr_mod", "pr_mod2", "pr_mod_exp",
    "p_modd", "p_modd2", "p_modd_exp"
  ),
  envir = .GlobalEnv
) # clean up the global environment

#export model summaries as markdown, PDF, and csv
model_summaries <- pretty_glmmTMB_summaries(models = models,
                                            file = file.path(
                                              deadwd_output_dir,
                                              "model_summaries.md"
                                            ),
                                            digits = 3)

combined_summaries <- bind_rows(
  lapply(names(models), function(m) {
    tidy(models[[m]], effects = "fixed", conf.int = TRUE) %>%
      mutate(model = m, .before = 1)
  })
)

write.csv(
  combined_summaries,
  file.path(deadwd_output_dir, "model_summaries.csv"),
  row.names = FALSE
)

extract_model_table_results <- function(model_list) {
  metadata <- bind_rows(lapply(names(model_list), function(model_name) {
    model <- model_list[[model_name]]
    model_family <- family(model)
    data.frame(
      model = model_name,
      family = model_family$family,
      link = model_family$link,
      observations = nobs(model),
      logLik = as.numeric(logLik(model)),
      AIC = AIC(model),
      stringsAsFactors = FALSE
    )
  }))

  fixed <- bind_rows(lapply(names(model_list), function(model_name) {
    tidy(model_list[[model_name]], effects = "fixed", conf.int = TRUE) %>%
      mutate(model = model_name, .before = 1)
  }))

  random <- bind_rows(lapply(names(model_list), function(model_name) {
    random_terms <- tryCatch(
      tidy(model_list[[model_name]], effects = "ran_pars"),
      error = function(e) data.frame()
    )
    if (nrow(random_terms) > 0) {
      random_terms <- random_terms %>%
        mutate(model = model_name, .before = 1)
    }
    random_terms
  }))

  list(metadata = metadata, fixed = fixed, random = random)
}

main_model_table_results <- extract_model_table_results(models)
saveRDS(
  main_model_table_results,
  file.path(deadwd_output_dir, "main_model_table_results.rds")
)

# Optional PDF output; uncomment this block if LuaLaTeX is available.
# rmarkdown::render(
#   file.path(deadwd_output_dir, "model_summaries.md"),
#   output_format = rmarkdown::pdf_document(
#     latex_engine = "lualatex"
#   )
# )

# --------------------------------------------------------------------
# 5.2 Sensitivity analyses
# --------------------------------------------------------------------
# Robustness checks supporting our model specifications and findings.
# Output from these models is reported as supplementary information.

# Complete-case datasets for imputation sensitivity analyses
log_data_complete <- log_data %>%
  filter(!is.na(mc_mass), !is.na(cwd_vol)) %>%
  mutate(
    rt_cwd = sqrt(cwd_vol),
    sc_cwd = as.numeric(scale(rt_cwd))
  ) # n = 173

# Scale raw moisture within treatment, matching mc_imp preprocessing
log_data_complete <- scale_within_treatment(
  df = log_data_complete,
  name_map = c(mc_mass = "sc_mctr")
)

log_data_p_complete <- subset(
  log_data_complete,
  host_abund > 0 | par_abund > 0
) # n = 120

# Coverage-standardized richness and Shannon-diversity sensitivity models.
diversity_sensitivity_models <- list(
  Host_richness_SC90 = qD_mod,
  Host_Shannon = glmmTMB(
    host_shannon ~ treatment + sc_mctr +
      sc_logtr + sc_cnpy + sc_loghatot + sc_cwd +
      (1 | plot_id),
    data = log_data,
    family = tweedie(link = "log")
  ),
  Host_Shannon_2 = glmmTMB(
    host_shannon ~ treatment + sc_mctr + ant_pres +
      sc_logtr + sc_cnpy + sc_cwd +
      (1 | site/plot_id),
    data = log_data,
    family = tweedie(link = "log")
  )
)

# Alternative measures of ant activity
ant_sensitivity_models <- list(
  Host_presence_ant_abundance = glmmTMB(
    host_pres ~ treatment + site + sc_logant + (1 | plot_id),
    data = log_data,
    family = binomial()
  ),
  Host_presence_plot_ant_activity = glmmTMB(
    host_pres ~ treatment + site + sc_wantoc + (1 | plot_id),
    data = log_data,
    family = binomial()
  ),
  Host_abundance_ant_abundance = glmmTMB(
    host_ab_tot ~ treatment + sc_logtr + sc_mctr + sc_logant +
      sc_cnpy + sc_cwd + (1 | site/plot_id),
    data = log_data,
    ziformula = ~ site + treatment,
    family = nbinom2()
  ),
  Host_abundance_plot_ant_activity = glmmTMB(
    host_ab_tot ~ treatment + sc_logtr + sc_mctr + sc_wantoc +
      sc_cnpy + sc_cwd + (1 | site/plot_id),
    data = log_data,
    ziformula = ~ site + treatment,
    family = nbinom2()
  )
)

# Refit every model using imputed moisture or CWD with complete cases
imputation_sensitivity_models <- list(
  Host_abundance_complete_cases = update(models[["Host_abundance"]], data = log_data_complete),
  Host_richness_complete_cases = update(models[["Host_richness"]], data = log_data_complete),
  Host_richness_2_complete_cases = update(models[["Host_richness_2"]], data = log_data_complete),
  Parasitoid_abundance_complete_cases = update(models[["Parasitoid_abundance"]], data = log_data_p_complete),
  Parasitoid_abundance_2_complete_cases = update(models[["Parasitoid_abundance_2"]], data = log_data_p_complete),
  Parasitoid_richness_complete_cases = update(models[["Parasitoid_richness"]], data = log_data_p_complete),
  Parasitoid_richness_2_complete_cases = update(models[["Parasitoid_richness2"]], data = log_data_p_complete),
  Parasitism_complete_cases = update(models[["Parasitism"]], data = log_data_p_complete),
  Parasitism_2_complete_cases = update(models[["Parasitism_2"]], data = log_data_p_complete)
)

sensitivity_models <- c(
  diversity_sensitivity_models,
  ant_sensitivity_models,
  imputation_sensitivity_models
)

rm(diversity_sensitivity_models, ant_sensitivity_models, imputation_sensitivity_models)

#export model summaries as markdown, PDF, and csv
rc_model_summaries <- pretty_glmmTMB_summaries(models = sensitivity_models,
  file = file.path(
    deadwd_output_dir,
    "sensitivity_model_summaries.md"
  ),
  digits = 3
)

combined_rc_summaries <- bind_rows(
  lapply(names(sensitivity_models), function(m) {
    tidy(sensitivity_models[[m]], effects = "fixed", conf.int = TRUE) %>%
      mutate(model = m, .before = 1)
  })
)

write.csv(
  combined_rc_summaries,
  file.path(deadwd_output_dir, "sensitivity_model_summaries.csv"),
  row.names = FALSE
)
sensitivity_model_table_results <- extract_model_table_results(
  sensitivity_models
)
saveRDS(
  sensitivity_model_table_results,
  file.path(deadwd_output_dir, "sensitivity_model_table_results.rds")
)

# Optional PDF output; uncomment this block if LuaLaTeX is available.
# rmarkdown::render(
#   file.path(deadwd_output_dir, "sensitivity_model_summaries.md"),
#   output_format = rmarkdown::pdf_document(
#     latex_engine = "lualatex"
#   )
# )

# --------------------------------------------------------------------
# 6. Community composition ####
# --------------------------------------------------------------------

host_meta <- hosts %>%
  distinct(sample_id, site, plot_id, treatment) %>%
  arrange(sample_id) # deadwood-level metadata for permanova

host_comm_tr <- host_comm[match(host_meta$sample_id, host_comm$sample_id), ]

host_comm_tr <- as.data.frame(host_comm_tr)
rownames(host_comm_tr) <- host_comm_tr$sample_id
host_comm_tr$sample_id <- NULL

summary(rowSums(host_comm_tr))         # total abundance per log
apply(host_comm_tr, 2, max)            # max per species
sort(colSums(host_comm_tr), decreasing = TRUE)[1:10]

colSums(host_comm_tr)  # Total abundance per species

host_comm_tr <- sqrt(host_comm_tr) #square root recommended due to a few highly dominant species

env_vars <- log_data %>%
  dplyr::select(sample_id, mc_imp, ant_pres)  

host_meta <- host_meta %>%
  left_join(env_vars, by = c("sample_id"))

host_meta <- host_meta %>%
  group_by(treatment) %>%
  mutate(
    sc_mc = scale(mc_imp)[,1],     # GMC scaled within each treatment
    ant_pres = ant_pres  
  ) %>%
  ungroup()

all(rownames(host_comm_tr) == host_meta$sample_id) # should be TRUE if you set rownames

nrow(host_comm_tr); nrow(host_meta)   

#now creating matrix and metadata for plot-level permanova

host_comm2 <- hosts %>%     # Species-by-plot matrix
  group_by(plot_id, morphotype) %>%
  summarise(abund = sum(number_individuals), .groups = "drop") %>%
  tidyr::pivot_wider(
    names_from  = morphotype,
    values_from = abund,
    values_fill = 0
  )

host_meta2 <- hosts %>%
  distinct(site, plot_id) %>%
  arrange(plot_id) # plot-level metadata for permanova

host_comm_tr2 <- host_comm2[match(host_meta2$plot_id, host_comm2$plot_id), ]

host_comm_tr2 <- as.data.frame(host_comm_tr2)
rownames(host_comm_tr2) <- host_comm_tr2$plot_id
host_comm_tr2$plot_id <- NULL

host_comm_tr2 <- sqrt(host_comm_tr2) #square root recommended due to a few highly dominant species

env_vars <- log_data %>%
  dplyr::select(site, plot_id, cnpy_prop, log_tr, wantoc_imp, rt_cwd) %>%
  dplyr::distinct(plot_id, .keep_all = TRUE)

env_vars <- env_vars %>%
  semi_join(host_meta2, by = c("site", "plot_id")) %>%
  group_by(plot_id) %>%
  slice_head(n = 1) %>%
  ungroup() # filter env_vars to only plots with hosts

# Now left_join
host_meta2 <- host_meta2 %>%
  left_join(env_vars, by = c("site", "plot_id"))

host_meta2 <- host_meta2 %>%
  mutate(
    sc_cnpy = scale(cnpy_prop)[, 1],
    sc_wantoc  = scale(wantoc_imp)[, 1],
    sc_logtr = scale(log_tr)[, 1],
    sc_cwd = scale(rt_cwd)[, 1])  # Scale environmental predictors


all(rownames(host_comm_tr2) == host_meta2$plot_id) # should be TRUE if you set rownames
nrow(host_comm_tr2); nrow(host_meta2)   


###
# PERMANOVA
###
set.seed(123)

adon_treat <- adonis2(
  host_comm_tr ~ treatment + sc_mc + ant_pres,
  data         = host_meta,
  method       = "bray",
  permutations = 1000,
  strata       = host_meta$plot_id,  # restrict permutations within plots
  by           = "margin"   #or "term" to perform Type I
)

adon_treat # treatment significantly affects community composition

bc_dist <- vegdist(host_comm_tr, method = "bray")

bd <- betadisper(bc_dist, host_meta$treatment)


anova(bd)              # parametric test
permutest(bd, permutations = 999)  # permutation-based test

host_meta <- as.data.frame(host_meta)  # force data.frame class

adon_treat2 <- pairwise.adonis2(
  host_comm_tr ~ treatment,
  data         = host_meta,
  nperm        = 1000,
  strata       = "plot_id"  # string name of column (quotes matter!)
)

adon_treat2 # G communities significantly different from SA and SnA


# Plot-level PERMANOVA
adon_env <- adonis2(
  host_comm_tr2 ~ sc_logtr + sc_cnpy + sc_wantoc,
  data         = host_meta2,
  method = "bray",
  binary = TRUE,          # use for turnover
  permutations = 1000,
  by           = "margin" 
)

adon_env 
# tree richness has a weak effect on community composition coming due to species turnover only
# see B-diversity analyses with MRM

# Abundance-based plot-level community composition
adon_env_nonbinary <- adonis2(
  host_comm_tr2 ~ sc_logtr + sc_cnpy + sc_wantoc,
  data         = host_meta2,
  method       = "bray",
  binary       = FALSE,
  permutations = 1000,
  by           = "margin"
)

adon_env_nonbinary

format_permanova_result <- function(result) {
  table <- as.data.frame(result)
  table$Term <- rownames(table)
  rownames(table) <- NULL
  table[, c("Term", setdiff(names(table), "Term")), drop = FALSE]
}

permanova_table_results <- list(
  deadwood_level = list(
    title = "Deadwood-level host community composition",
    method = "Bray-Curtis; permutations restricted within plots",
    binary = FALSE,
    table = format_permanova_result(adon_treat)
  ),
  plot_level_nonbinary = list(
    title = "Plot-level host community composition (abundance-based)",
    method = "Bray-Curtis",
    binary = FALSE,
    table = format_permanova_result(adon_env_nonbinary)
  ),
  plot_level_binary = list(
    title = "Plot-level host community composition (incidence-based)",
    method = "Binary Bray-Curtis",
    binary = TRUE,
    table = format_permanova_result(adon_env)
  )
)

saveRDS(
  permanova_table_results,
  file.path(deadwd_output_dir, "permanova_table_results.rds")
)

bc_dist <- vegdist(host_comm_tr2, method = "bray")
bd <- betadisper(bc_dist, host_meta2$sc_logtr)

anova(bd)              # parametric test
permutest(bd, permutations = 999)  # permutation-based test

###
# dbRDA
###

host_meta3 <- hosts %>%
  distinct(sample_id, site, plot_id, treatment) %>%
  arrange(sample_id)

env_vars <- log_data %>%
  dplyr::select(sample_id, site, plot_id, treatment,
                cnpy_prop, rt_cwd, log_tr, ant_pres, mc_imp)  

host_meta3 <- host_meta3 %>%
  left_join(env_vars, by = c("sample_id", "site", "plot_id", "treatment"))

host_meta3 <- host_meta3 %>%
  mutate(
    sc_logtr = scale(log_tr)[, 1]
  )  # Scale environmental predictors

host_cap <- capscale(
  host_comm_tr ~ treatment + sc_logtr,
  data     = host_meta3,
  distance = "bray"
)

anova(host_cap, by = "margin", permutations = 999)

RsquareAdj(host_cap)

#extract information from dbRDA for ordination
#extract plot and species scores
site_sc <- as.data.frame(scores(host_cap, display = "sites", choices = 1:2))

site_sc$sample_id <- rownames(site_sc)

host_sites_plot_env <- host_meta3 %>%
  inner_join(site_sc, by = "sample_id")

host_sites_plot_env <- host_sites_plot_env %>% # adding host abundance to plot point size
  left_join(
    log_data %>% dplyr::select(host_ab_tot, sample_id),
    by = "sample_id"
  )

env_fit <- envfit(
  host_cap ~ treatment + sc_logtr,
  data = host_meta3,
  permutations = 1000
)

eig <- eigenvals(host_cap, constrained = TRUE)
perc <- eig / sum(eig) * 100

spec_scores <- as.data.frame(
  scores(host_cap, display = "species", choices = 1:2)
)
spec_scores$morphotype <- rownames(spec_scores)

spec_scores$abs_score <- sqrt(spec_scores$CAP1^2 + spec_scores$CAP2^2)
top_species <- spec_scores %>%
  arrange(desc(abs_score)) %>%
  slice(1:3) # pick top 3 species

species_scaler <- 1.4   # or 6, or use ordiArrowMul

top_species$CAP1_scaled <- top_species$CAP1 * species_scaler
top_species$CAP2_scaled <- top_species$CAP2 * species_scaler


##
# Indicator species analysis
##

# 1) metadata: one row per block, including uncolonized
meta_blocks <- log_data %>%
  distinct(log_id, treatment, position)  # adjust names

# 2) host counts per block x species (colonized only in raw, but we'll complete with zeros)
host_comm <- insect_data %>%
  filter(level == "host") %>%
  group_by(log_id, morphotype) %>%
  summarise(abund = sum(number_individuals), .groups = "drop") %>%
  pivot_wider(names_from = morphotype, values_from = abund, values_fill = 0)

# 3) add missing blocks as all-zero rows
host_comm_full <- meta_blocks %>%
  left_join(host_comm, by = "log_id") %>%
  mutate(across(-c(log_id, treatment, position), ~tidyr::replace_na(.x, 0)))

X <- host_comm_full %>%
  dplyr::select(-log_id, -treatment, -position) %>%
  as.matrix()

group_placement <- factor(host_comm_full$position)   # S vs G
group_treatment  <- factor(host_comm_full$treatment) # A, nA, G

ind_pos <- multipatt(X, group_placement, func="IndVal.g", control=how(nperm=999))
summary(ind_pos, alpha=0.05, indvalcomp = TRUE)

ind_trt <- multipatt(X, group_treatment, func="IndVal.g", control=how(nperm=999))
summary(ind_trt, alpha=0.05, indvalcomp = TRUE)


# --------------------------------------------------------------------
# 7. Beta-diversity ####
# --------------------------------------------------------------------
# First at deadwood treatment level (single pariwise comparison)
# presence–absence matrix S vs G (hosts)
host_pa_mat <- insect_data %>%
  filter(level == "host",
         !is.na(location),
         !is.na(morphotype)) %>%
  distinct(location, morphotype) %>%
  mutate(pres = 1) %>%
  pivot_wider(
    names_from  = morphotype,
    values_from = pres,
    values_fill = 0
  ) %>%
  mutate(location = factor(location, levels = c("S", "G"))) %>%
  arrange(location) %>%
  {
    mat <- as.matrix(dplyr::select(., -location))
    rownames(mat) <- .$location
    mat
  }

# Baselga decomposition (Sørensen family)
host_beta_pair <- beta.pair(host_pa_mat, index.family = "sorensen")

sor_mat  <- as.matrix(host_beta_pair$beta.sor)
sim_mat  <- as.matrix(host_beta_pair$beta.sim)
sne_mat  <- as.matrix(host_beta_pair$beta.sne)

beta_summary <- tibble(
  pair      = "S–G",
  beta_sor  = sor_mat["S", "G"],
  beta_turn = sim_mat["S", "G"],
  beta_nest = sne_mat["S", "G"]
) %>%
  mutate(
    prop_turn = beta_turn / beta_sor,
    prop_nest = beta_nest / beta_sor
  )

beta_summary # results

message("Script ran successfully ✔️")
