# clearing workspace
rm(list = ls())
graphics.off()
cat("\014")

# --------------------------------------------------------------------
## Header ##
# Running title: Moisture limits the diversity of nesting bees, wasps,
# and parasitoids in lying and standing deadwood
# Author: Massimo Martini
# Date: 28th August 2026
# Description: This script runs the path analyses used in the manuscript
# Before running this script, run "deadwd_script.R"

# --------------------------------------------------------------------

# Set working directory if needed
# setwd()

# --------------------------------------------------------------------
# 1. Load libraries
# --------------------------------------------------------------------

library(dplyr)
library(glmmTMB)
library(DHARMa)
library(performance)
library(piecewiseSEM)
library(emmeans)

if (!requireNamespace("multcompView", quietly = TRUE)) {
  stop(
    "Package 'multcompView' is required by the path-analysis coefficient workflow."
  )
}

# --------------------------------------------------------------------
# 2. Import trap-level data
# --------------------------------------------------------------------

# Allow the script to be run either from the project root or from
# Revision/Revised_R.
data_dir <- if (file.exists("log_data.csv")) {
  "."
} else {
  file.path("Revision", "Revised_R")
}

log_data_path <- file.path(data_dir, "log_data.csv")

if (!file.exists(log_data_path)) {
  stop(
    "Could not find log_data.csv. Run this script from the project root ",
    "or from Revision/Revised_R."
  )
}

# Keep all files generated by this script in one directory.
path_output_dir <- file.path(data_dir, "path_analysis_output")
dir.create(path_output_dir, recursive = TRUE, showWarnings = FALSE)

log_data <- readr::read_csv(log_data_path, show_col_types = FALSE)

source(file.path(data_dir, "deadwd_functions.R"))

# --------------------------------------------------------------------
# 3. Calculate and transform variables
# --------------------------------------------------------------------

log_data$log_tr <- log2(log_data$tree_r)

log_data <- log_data %>%
  mutate(
    host_abund_tot = par_abund + host_abund,
    p_rate = if_else(
      host_abund_tot > 0,
      par_abund / host_abund_tot,
      NA_real_
    )
  )

log_data$log_hatot <- log1p(log_data$host_abund_tot)

# Bound apparent parasitism strictly inside (0, 1) for beta regression.
# Apparent parasitism remains NA when no brood outcome was observed.
log_data$p_rate2 <- pmin(
  pmax(log_data$p_rate, 0.0001),
  1 - 0.0001
)

# Set factors and reference levels.
log_data$treatment <- relevel(factor(log_data$treatment), ref = "nA")
log_data$ant_pres <- factor(log_data$ant_pres)
log_data$ant_pres_num <- as.numeric(as.character(log_data$ant_pres))
log_data$site <- factor(log_data$site)
log_data$plot_id <- factor(log_data$plot_id)

# --------------------------------------------------------------------
# 4. Prepare aligned datasets for the path analysis
# --------------------------------------------------------------------

# Confirm that log_id provides one stable identifier per trap. This is
# needed to align component datasets with the master SEM dataset.
if (anyDuplicated(log_data$log_id)) {
  stop("log_id must uniquely identify every trap before fitting the path analysis.")
}

# Master trap-level dataset. Host component models can use all rows.
sem_data <- log_data

# Conditional dataset for parasitoid and apparent-parasitism components.
# Parasitoid emergence is itself evidence that host brood was present.
sem_data_p <- sem_data %>%
  filter(host_abund_tot > 0)

# Conditional dataset for moisture content component
sem_data_mc <- sem_data %>%
  filter(!is.na(mc_mass))

# One row per plot for components involving only plot-level responses,
# such as a canopy-cover response model.
sem_data_plot <- sem_data %>%
  arrange(site, plot_id, log_id) %>%
  distinct(site, plot_id, .keep_all = TRUE)

stopifnot(
  all(sem_data_p$host_abund_tot > 0),
  all(!is.na(sem_data_p$p_rate)),
  !anyDuplicated(sem_data_p$log_id),
  !anyDuplicated(sem_data_plot$plot_id)
)

# Full 192-row dataset used by the pSEM and d-separation tests.
sem_data_master <- sem_data %>%
  mutate(
    par_rich = if_else(
      host_abund_tot > 0,
      par_rich,
      NA_integer_
    )
  )

stopifnot(
  nrow(sem_data_master) == 192,
  sum(!is.na(sem_data_master$par_rich)) == nrow(sem_data_p)
)

# --------------------------------------------------------------------
# 5. Path analyses
# --------------------------------------------------------------------

#### > 5.1 Response-specific path analysis ####
# Response-specific component models
# Standardized response-scale average marginal effects are calculated manually

# Apparent-parasitism component model. This mirrors the predictor and
# random-effect structure of p_modd in deadwd_script.R, but uses the
# bounded apparent-parasitism rate required by beta regression.
prt_sem <- glmmTMB(
  p_rate2 ~ treatment + mc_imp + ant_pres_num +
    par_rich + host_rich + log_tr + cnpy_prop +
    (1 | site/plot_id),
  data = sem_data_p,
  family = beta_family(link = "logit")
)

# Parasitoid-richness component model. Parasitoid abundance is omitted
# both as a response and as a predictor because it is strongly correlated
# with parasitoid richness.
pr_sem <- glm(
  par_rich ~ treatment + host_rich + log_hatot + ant_pres_num + mc_imp +
    log_tr + cnpy_prop,
  data = sem_data_p,
  family = poisson()
)

# Host-richness component model.
hr_sem <- glmmTMB(
  host_rich ~ treatment + mc_imp + log_tr + cnpy_prop +
    log_hatot +
    (1 | plot_id),
  data = sem_data,
  family = genpois()
)

# Total-host-abundance component model. Total host abundance includes
# both successfully emerged hosts and hosts from which parasitoids emerged.
ha_sem <- glmmTMB(
  log_hatot ~ treatment + log_tr + mc_imp + ant_pres_num +
    cnpy_prop +
    (1 | site/plot_id),
  data = sem_data,
  ziformula = ~ site + treatment,
  family = ziGamma(link = "log")
)

# Moisture-content component model.
mc_sem <- glmmTMB(
  mc_imp ~ treatment + log_tr + cnpy_prop +
    (1 | site/plot_id),
  data = sem_data_mc,
  dispformula = ~ site + treatment,
  family = beta_family()
)

# Ant-occurrence component model.
ant_sem <- glmmTMB(
  ant_pres_num ~ treatment + log_tr + cnpy_prop +
    (1 | site/plot_id),
  data = sem_data,
  family = binomial()
)

# Canopy cover is measured at plot level, so retain one row per plot for
# this component rather than repeating the same response for every trap.
cnpy_sem <- glmmTMB(
  cnpy_prop ~ log_tr +
    (1 | site),
  data = sem_data_plot,
  family = gaussian(link = "identity")
)

# Assemble the component models while retaining the dataset used to fit
# each component. Supplying the complete trap-level dataset follows the
# approach used by Schnabel et al. for component models fitted to different
# datasets.
sem_mods <- list(
  prt_sem  = prt_sem,
  pr_sem   = pr_sem,
  hr_sem   = hr_sem,
  ha_sem   = ha_sem,
  mc_sem   = mc_sem,
  ant_sem  = ant_sem,
  cnpy_sem = cnpy_sem,
  ant_pres_num %~~% mc_imp, # correlation relates to plot geomorphology
  log_hatot %~~% p_rate2
)

sem_all <- do.call(
  piecewiseSEM::psem,
  c(sem_mods, list(data = sem_data_master))
)

# piecewiseSEM >= 2.3 reconstructs its data slot from the component model
# frames. Restore the explicitly supplied master dataset so rows from the
# differently sized component datasets are not combined by row position.
sem_all$data <- sem_data_master

sem_coef <- coefs(
  sem_all,
  standardize = "none",
  test.statistic = "LR"
)

sem_dsep <- dSep(
  sem_all,
  conserve = TRUE
)

sem_fisher <- fisherC(sem_dsep)

sem_aic <- AIC_psem(
  sem_all,
  AIC.type = "loglik",
  conserve = TRUE
)

sem_r2 <- rsquared(sem_all)

sem_coef
sem_fisher
sem_dsep
sem_aic
sem_r2

# Calculate standardized response-scale effects for every continuous
# predictor in the component models. Factors and binary variables are omitted.
sem_model_list <- sem_mods[
  vapply(
    sem_mods,
    function(x) inherits(x, c("glm", "lm", "glmmTMB")),
    logical(1)
  )
]

standardized_paths <- do.call(
  rbind,
  lapply(names(sem_model_list), function(model_name) {
    model <- sem_model_list[[model_name]]
    dat <- model.frame(model)

    variables <- all.vars(lme4::nobars(formula(model)))
    predictors <- setdiff(variables, variables[1])

    continuous_predictors <- predictors[
      vapply(
        predictors,
        function(x) {
          x %in% names(dat) &&
            is.numeric(dat[[x]]) &&
            dplyr::n_distinct(dat[[x]], na.rm = TRUE) > 2
        },
        logical(1)
      )
    ]

    results <- lapply(
      continuous_predictors,
      function(x) standardized_path(model, x)
    )

    result <- do.call(rbind, results)
    result$Model <- model_name
    result
  })
)

rownames(standardized_paths) <- NULL
standardized_paths

#### > 5.2 Standardized path analysis ####
# Gaussian component models
# Standardized coefficients calculated automatically by piecewiseSEM

# First, transform and scale variables. Each SEM node is scaled once using
# its designated reference population, rather than being rescaled separately
# in every component model. This keeps a given node in the same units along
# all incoming and outgoing pathways.
sem_gauss <- sem_data %>%
  mutate(
    tr_prate = if_else(
      host_abund_tot > 0,
      qlogis((par_abund + 0.5) / (host_abund_tot + 1)),
      NA_real_
    ),
    tr_par_rich = if_else(host_abund_tot > 0, sqrt(par_rich), NA_real_),
    tr_host_rich = sqrt(host_rich),
    tr_host_abund = log1p(host_abund_tot),
    tr_mc = log(mc_imp),
    tr_logtr = log_tr,
    tr_cnpy = cnpy_prop
  )

# Standardize a variable using the mean and SD from a specified reference
# population while applying those same constants to every observation.
scale_from_reference <- function(x, reference) {
  reference_mean <- mean(reference, na.rm = TRUE)
  reference_sd <- sd(reference, na.rm = TRUE)

  if (!is.finite(reference_sd) || reference_sd == 0) {
    stop("Reference SD must be finite and greater than zero.")
  }

  as.numeric((x - reference_mean) / reference_sd)
}

parasitoid_reference <- sem_gauss$host_abund_tot > 0
plot_reference <- !duplicated(sem_gauss$plot_id)

# Parasitoid nodes are defined for traps with evidence of host brood.
sem_gauss$z_prate <- scale_from_reference(
  sem_gauss$tr_prate,
  sem_gauss$tr_prate[parasitoid_reference]
)
sem_gauss$z_par_rich <- scale_from_reference(
  sem_gauss$tr_par_rich,
  sem_gauss$tr_par_rich[parasitoid_reference]
)

# Host and moisture nodes use the complete trap-level reference population.
sem_gauss$z_host_rich <- scale_from_reference(
  sem_gauss$tr_host_rich,
  sem_gauss$tr_host_rich
)
sem_gauss$z_host_abund <- scale_from_reference(
  sem_gauss$tr_host_abund,
  sem_gauss$tr_host_abund
)
sem_gauss$z_mc <- scale_from_reference(
  sem_gauss$tr_mc,
  sem_gauss$tr_mc
)

# Tree richness and canopy cover are plot-level variables, so their scaling
# constants are calculated from one observation per plot.
sem_gauss$z_logtr <- scale_from_reference(
  sem_gauss$tr_logtr,
  sem_gauss$tr_logtr[plot_reference]
)
sem_gauss$z_cnpy <- scale_from_reference(
  sem_gauss$tr_cnpy,
  sem_gauss$tr_cnpy[plot_reference]
)

# Prepare the component-specific datasets only after all transformations and
# scaling constants have been applied to the master Gaussian-SEM dataset.
sem_gauss_p <- sem_gauss %>%
  filter(host_abund_tot > 0)

sem_gauss_mc <- sem_gauss %>%
  filter(!is.na(mc_mass))

sem_gauss_plot <- sem_gauss %>%
  arrange(site, plot_id, log_id) %>%
  distinct(site, plot_id, .keep_all = TRUE)

stopifnot(
  all(is.finite(sem_gauss_p$z_prate)),
  all(is.finite(sem_gauss_p$z_par_rich)),
  all(is.finite(sem_gauss$z_host_rich)),
  all(is.finite(sem_gauss$z_host_abund)),
  all(is.finite(sem_gauss$z_mc)),
  all(is.finite(sem_gauss$z_logtr)),
  all(is.finite(sem_gauss$z_cnpy)),
  !anyDuplicated(sem_gauss_p$log_id),
  !anyDuplicated(sem_gauss_plot$plot_id)
)

# Full Gaussian component models. These retain the same hypothesized
# pathways as the response-specific models
prt_sem_gauss <- glmmTMB(
  z_prate ~ treatment + z_mc + ant_pres_num +
    z_par_rich + z_host_rich + z_logtr + z_cnpy +
    (1 | site/plot_id),
  data = sem_gauss_p,
  family = gaussian(link = "identity")
)

pr_sem_gauss <- glmmTMB(
  z_par_rich ~ treatment + z_host_rich + z_host_abund +
    ant_pres_num + z_mc + z_logtr + z_cnpy +
    (1 | plot_id),
  data = sem_gauss_p,
  family = gaussian(link = "identity")
)

hr_sem_gauss <- glmmTMB(
  z_host_rich ~ treatment + z_mc + z_logtr + z_cnpy +
    z_host_abund +
    (1 | plot_id),
  data = sem_gauss,
  family = gaussian(link = "identity")
)
  
ha_sem_gauss <- glmmTMB(
  z_host_abund ~ treatment + z_logtr + z_mc + ant_pres_num +
    z_cnpy +
    (1 | site/plot_id),
  data = sem_gauss,
  family = gaussian(link = "identity")
)

mc_sem_gauss <- glmmTMB(
  z_mc ~ treatment + z_logtr + z_cnpy +
    (1 | site/plot_id),
  data = sem_gauss_mc,
  family = gaussian(link = "identity")
)

ant_sem_gauss <- glmmTMB(
  ant_pres_num ~ treatment + z_logtr + z_cnpy +
    (1 | site/plot_id),
  data = sem_gauss,
  family = binomial()
)

cnpy_sem_gauss <- glmmTMB(
  z_cnpy ~ z_logtr +
    (1 | site),
  data = sem_gauss_plot,
  family = gaussian(link = "identity")
)

# Assemble the full Gaussian path analysis using the same pathway structure
# and correlated error as the response-specific path analysis.
sem_mods_gauss <- list(
  prt_sem_gauss  = prt_sem_gauss,
  pr_sem_gauss   = pr_sem_gauss,
  hr_sem_gauss   = hr_sem_gauss,
  ha_sem_gauss   = ha_sem_gauss,
  mc_sem_gauss   = mc_sem_gauss,
  ant_sem_gauss  = ant_sem_gauss,
  cnpy_sem_gauss = cnpy_sem_gauss,
  ant_pres_num %~~% z_mc,
  z_host_abund %~~% z_prate
)

sem_all_gauss <- do.call(
  piecewiseSEM::psem,
  c(sem_mods_gauss, list(data = sem_gauss))
)

# Restore the explicitly supplied master dataset because piecewiseSEM >= 2.3
# otherwise reconstructs it from the differently sized component frames.
sem_all_gauss$data <- sem_gauss

# Extract the pSEM results separately. summary.psem() also calculates a
# likelihood-ratio chi-square by refitting saturated component models on the
# master dataset; that comparison is not defined for components fitted to
# different datasets and sample sizes.
sem_coef_gauss <- coefs(
  sem_all_gauss,
  standardize = "none",
  test.statistic = "LR"
)

sem_dsep_gauss <- dSep(
  sem_all_gauss,
  conserve = TRUE
)

sem_fisher_gauss <- fisherC(sem_dsep_gauss)

sem_aic_gauss <- AIC_psem(
  sem_all_gauss,
  AIC.type = "dsep",
  conserve = TRUE
)

sem_r2_gauss <- rsquared(sem_all_gauss)

sem_coef_gauss
sem_fisher_gauss
sem_aic_gauss
sem_r2_gauss


#### > 5.3 Parsimonious path analyses ####
# Stepwise variable removal is performed on the response-specific
# path analysis, while motiroting AIC and overall model fit.

prt_sem2 <- glmmTMB(
  p_rate2 ~ treatment + mc_imp + 
    par_rich + host_rich + cnpy_prop +
    (1 | site/plot_id),
  data = sem_data_p,
  family = beta_family(link = "logit")
)

pr_sem2 <- glm(
  par_rich ~ treatment + log_hatot + mc_imp + cnpy_prop,
  data = sem_data_p,
  family = poisson()
)

hr_sem2 <- glmmTMB(
  host_rich ~ log_tr + cnpy_prop + log_hatot +
    (1 | plot_id),
  data = sem_data,
  family = genpois()
)

ha_sem2 <- glmmTMB(
  log_hatot ~ treatment + log_tr + mc_imp +
    cnpy_prop +
    (1 | site/plot_id),
  data = sem_data,
  ziformula = ~ site + treatment,
  family = ziGamma(link = "log")
)

mc_sem2 <- glmmTMB(
  mc_imp ~ treatment + log_tr + cnpy_prop +
    (1 | site/plot_id),
  data = sem_data_mc,
  dispformula = ~ site + treatment,
  family = beta_family()
)

ant_sem2 <- glmmTMB(
  ant_pres_num ~ treatment + log_tr + cnpy_prop +
    (1 | site/plot_id),
  data = sem_data,
  family = binomial()
)

sem_mods2 <- list(
  prt_sem2  = prt_sem2,
  pr_sem2   = pr_sem2,
  hr_sem2   = hr_sem2,
  ha_sem2   = ha_sem2,
  mc_sem2   = mc_sem2,
  ant_sem2  = ant_sem2,
  cnpy_sem = cnpy_sem,
  ant_pres_num %~~% mc_imp, # correlation relates to plot geomorphology
  log_hatot %~~% p_rate2 # mathematical correlation
)

sem_all2 <- do.call(
  piecewiseSEM::psem,
  c(sem_mods2, list(data = sem_data_master))
)

sem_all2$data <- sem_data_master

sem_coef2 <- coefs(
  sem_all2,
  standardize = "none",
  test.statistic = "LR"
)

sem_dsep2 <- dSep(
  sem_all2,
  conserve = TRUE
)

sem_fisher2 <- fisherC(sem_dsep2)

sem_aic2 <- AIC_psem(
  sem_all2,
  AIC.type = "loglik",
  conserve = TRUE
)

sem_r2_2 <- rsquared(sem_all2)

sem_coef2
sem_fisher2
sem_dsep2
sem_aic2
sem_r2_2

# Planned treatment contrasts for the parsimonious response-specific SEM.
# The treatment-factor order is nA, A, G.

# Ground contact versus the two standing treatments for host abundance.
emm_ha2 <- emmeans(ha_sem2, ~ treatment)
contrast_ha2 <- contrast(
  emm_ha2,
  method = list(G_vs_standing = c(-0.5, -0.5, 1))
)

# Ground contact versus the two standing treatments for moisture content.
emm_mc2 <- emmeans(mc_sem2, ~ treatment)
contrast_mc2 <- contrast(
  emm_mc2,
  method = list(G_vs_standing = c(-0.5, -0.5, 1))
)

emm_ant2 <- emmeans(ant_sem2, ~ treatment)

# Ant exclusion versus the two ant-accessible treatments for ant presence.
contrast_ant_exclusion2 <- contrast(
  emm_ant2,
  method = list(nA_vs_access = c(1, -0.5, -0.5)),
  adjust = "none"
)

# Ground contact versus ant-access standing deadwood for ant presence.
contrast_ant_ground2 <- contrast(
  emm_ant2,
  method = list(G_vs_A_only = c(0, -1, 1)),
  adjust = "none"
)

contrast_ha2
contrast_mc2
contrast_ant_exclusion2
contrast_ant_ground2

# The same parsimonious structure is applied to the standardized
# path analysis to extract coefficients for Fig. 3

prt_sem_gauss2 <- glmmTMB(
  z_prate ~ treatment + z_mc +
    z_par_rich + z_host_rich + z_cnpy +
    (1 | site/plot_id),
  data = sem_gauss_p,
  family = gaussian(link = "identity")
)

pr_sem_gauss2 <- glmmTMB(
  z_par_rich ~ treatment + z_host_abund +
    z_mc + z_cnpy +
    (1 | plot_id),
  data = sem_gauss_p,
  family = gaussian(link = "identity")
)

hr_sem_gauss2 <- glmmTMB(
  z_host_rich ~ z_logtr + z_cnpy + z_host_abund +
    (1 | plot_id),
  data = sem_gauss,
  family = gaussian(link = "identity")
)

ha_sem_gauss2 <- glmmTMB(
  z_host_abund ~ treatment + z_logtr + z_mc + z_cnpy +
    (1 | site/plot_id),
  data = sem_gauss,
  family = gaussian(link = "identity")
)

mc_sem_gauss2 <- glmmTMB(
  z_mc ~ treatment + z_logtr + z_cnpy +
    (1 | site/plot_id),
  data = sem_gauss_mc,
  family = gaussian(link = "identity")
)

ant_sem_gauss2 <- glmmTMB(
  ant_pres_num ~ treatment + z_logtr + z_cnpy +
    (1 | site/plot_id),
  data = sem_gauss,
  family = binomial()
)

# Assemble the full Gaussian path analysis using the same pathway structure
# and correlated error as the response-specific path analysis.
sem_mods_gauss2 <- list(
  prt_sem_gauss2  = prt_sem_gauss2,
  pr_sem_gauss2   = pr_sem_gauss2,
  hr_sem_gauss2   = hr_sem_gauss2,
  ha_sem_gauss2   = ha_sem_gauss2,
  mc_sem_gauss2   = mc_sem_gauss2,
  ant_sem_gauss2  = ant_sem_gauss2,
  cnpy_sem_gauss = cnpy_sem_gauss,
  ant_pres_num %~~% z_mc,
  z_host_abund %~~% z_prate
)

sem_all_gauss2 <- do.call(
  piecewiseSEM::psem,
  c(sem_mods_gauss2, list(data = sem_gauss))
)

# Restore the explicitly supplied master dataset because piecewiseSEM >= 2.3
# otherwise reconstructs it from the differently sized component frames.
sem_all_gauss2$data <- sem_gauss

# Extract the pSEM results separately. summary.psem() also calculates a
# likelihood-ratio chi-square by refitting saturated component models on the
# master dataset; that comparison is not defined for components fitted to
# different datasets and sample sizes.
sem_coef_gauss2 <- coefs(
  sem_all_gauss2,
  standardize = "none",
  test.statistic = "LR"
)

sem_dsep_gauss2 <- dSep(
  sem_all_gauss2,
  conserve = TRUE
)

sem_fisher_gauss2 <- fisherC(sem_dsep_gauss2)

sem_aic_gauss2 <- AIC_psem(
  sem_all_gauss2,
  AIC.type = "dsep",
  conserve = TRUE
)

sem_r2_gauss2 <- rsquared(sem_all_gauss2)

sem_coef_gauss2
sem_fisher_gauss2
sem_dsep_gauss2
sem_aic_gauss2
sem_r2_gauss2

# Planned treatment contrasts for the parsimonious Gaussian SEM.
# These match the response-specific contrasts above and provide estimates
# on the scale used for the standardized SEM figure.

# Ground contact versus the two standing treatments for host abundance.
emm_ha_gauss2 <- emmeans(ha_sem_gauss2, ~ treatment)
contrast_ha_gauss2 <- contrast(
  emm_ha_gauss2,
  method = list(G_vs_standing = c(-0.5, -0.5, 1))
)

# Ground contact versus the two standing treatments for moisture content.
emm_mc_gauss2 <- emmeans(mc_sem_gauss2, ~ treatment)
contrast_mc_gauss2 <- contrast(
  emm_mc_gauss2,
  method = list(G_vs_standing = c(-0.5, -0.5, 1))
)

emm_ant_gauss2 <- emmeans(ant_sem_gauss2, ~ treatment)

# Ant exclusion versus the two ant-accessible treatments for ant presence.
contrast_ant_exclusion_gauss2 <- contrast(
  emm_ant_gauss2,
  method = list(nA_vs_access = c(1, -0.5, -0.5)),
  adjust = "none"
)

# Ground contact versus ant-access standing deadwood for ant presence.
contrast_ant_ground_gauss2 <- contrast(
  emm_ant_gauss2,
  method = list(G_vs_A_only = c(0, -1, 1)),
  adjust = "none"
)

contrast_ha_gauss2
contrast_mc_gauss2
contrast_ant_exclusion_gauss2
contrast_ant_ground_gauss2

combine_contrast_info <- function(
  response,
  response_specific_contrast,
  gaussian_contrast
) {
  response_specific <- as.data.frame(response_specific_contrast)
  gaussian <- as.data.frame(gaussian_contrast)

  if (!identical(response_specific$contrast, gaussian$contrast)) {
    stop("Response-specific and Gaussian treatment contrasts do not match.")
  }

  data.frame(
    Response = response,
    Contrast = response_specific$contrast,
    Response_specific_estimate = response_specific$estimate,
    Response_specific_SE = response_specific$SE,
    Response_specific_df = response_specific$df,
    Response_specific_test_statistic = response_specific$z.ratio,
    Response_specific_P = response_specific$p.value,
    Gaussian_estimate = gaussian$estimate,
    Gaussian_SE = gaussian$SE,
    Gaussian_df = gaussian$df,
    Gaussian_test_statistic = gaussian$z.ratio,
    Gaussian_P = gaussian$p.value,
    check.names = FALSE
  )
}

sem_contrast_results <- bind_rows(
  combine_contrast_info(
    "Total host abundance",
    contrast_ha2,
    contrast_ha_gauss2
  ),
  combine_contrast_info(
    "Moisture content",
    contrast_mc2,
    contrast_mc_gauss2
  ),
  combine_contrast_info(
    "Ant presence",
    contrast_ant_exclusion2,
    contrast_ant_exclusion_gauss2
  ),
  combine_contrast_info(
    "Ant presence",
    contrast_ant_ground2,
    contrast_ant_ground_gauss2
  )
)

sem_contrast_results

# Export the coefficient tables
sem_table_results <- list(
  full_response = as.data.frame(sem_coef),
  full_gaussian = as.data.frame(sem_coef_gauss),
  parsimonious_response = as.data.frame(sem_coef2),
  parsimonious_gaussian = as.data.frame(sem_coef_gauss2),
  parsimonious_contrasts = sem_contrast_results
)

sem_table_results_path <- file.path(
  path_output_dir,
  "sem_table_results.rds"
)
saveRDS(sem_table_results, sem_table_results_path)

message("Exported SEM table results to: ", sem_table_results_path)
message("Script ran successfully ✔️")
